# design_analysis_ex31.tcl
# if dcp is generated by routed_design
set xnets [xilinx::designutils::get_sll_nets]
# if dcp is generated by placed_design
set xnets [xilinx::designutils::get_sll_nets]
set xneta [xilinx::designutils::get_inter_slr_nets]
set xnets [filter $xneta "TYPE != GLOBAL_CLOCK"]
set xnets_len [llength $xnets]
set paths [get_timing_paths -nworst 1 -max $xnets_len \
    -through $xnets -filter {INTER_SLR_COMPENSATION != ""}]

